[[redirects]]
  from = "/api/v2/*"
  to = "https://io.adafruit.com/api/v2/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://cacao-care.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
